const data = [
	{
		id: 1,
		dateOfSeizure: "2019-01-01",
		goodsType: "Cattle",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Benapole",
		seizedBy: "Patrol team S2",
		currentOwner: "BGB Sector 2",
		smugglerCaught: false,
	},
	{
		id: 2,
		dateOfSeizure: "2019-01-01",
		goodsType: "Weed",
		quantity: "4100",
		unit: "gms",
		seizedAt: "Rajshahi",
		seizedBy: "Patrol team S41",
		currentOwner: "BGB Sector 4",
		smugglerCaught: true,
	},
	{
		id: 3,
		dateOfSeizure: "2019-01-01",
		dateOfDemolition: "2019-06-01",
		goodsType: "Clothes",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Cumilla",
		seizedBy: "Patrol team S12",
		currentOwner: "Customs",
		monetrayValue: "100000",
		smugglerCaught: false,
	},
	{
		id: 4,
		dateOfSeizure: "2019-01-01",
		goodsType: "Cattle",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Benapole",
		seizedBy: "Patrol team S2",
		currentOwner: "BGB Sector 2",
		smugglerCaught: false,
	},
	{
		id: 5,
		dateOfSeizure: "2019-01-01",
		goodsType: "Weed",
		quantity: "4100",
		unit: "gms",
		seizedAt: "Rajshahi",
		seizedBy: "Patrol team S41",
		currentOwner: "BGB Sector 4",
		smugglerCaught: true,
	},
	{
		id: 6,
		dateOfSeizure: "2019-01-01",
		dateOfDemolition: "2019-06-01",
		goodsType: "Clothes",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Cumilla",
		seizedBy: "Patrol team S12",
		currentOwner: "Customs",
		monetrayValue: "100000",
		smugglerCaught: false,
	},
	{
		id: 7,
		dateOfSeizure: "2019-01-01",
		goodsType: "Cattle",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Benapole",
		seizedBy: "Patrol team S2",
		currentOwner: "BGB Sector 2",
		smugglerCaught: false,
	},
	{
		id: 8,
		dateOfSeizure: "2019-01-01",
		goodsType: "Weed",
		quantity: "4100",
		unit: "gms",
		seizedAt: "Rajshahi",
		seizedBy: "Patrol team S41",
		currentOwner: "BGB Sector 4",
		smugglerCaught: true,
	},
	{
		id: 9,
		dateOfSeizure: "2019-01-01",
		dateOfDemolition: "2019-06-01",
		goodsType: "Clothes",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Cumilla",
		seizedBy: "Patrol team S12",
		currentOwner: "Customs",
		monetrayValue: "100000",
		smugglerCaught: false,
	},
	{
		id: 10,
		dateOfSeizure: "2019-01-01",
		goodsType: "Cattle",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Benapole",
		seizedBy: "Patrol team S2",
		currentOwner: "BGB Sector 2",
		smugglerCaught: false,
	},
	{
		id: 11,
		dateOfSeizure: "2019-01-01",
		goodsType: "Weed",
		quantity: "4100",
		unit: "gms",
		seizedAt: "Rajshahi",
		seizedBy: "Patrol team S41",
		currentOwner: "BGB Sector 4",
		smugglerCaught: true,
	},
	{
		id: 12,
		dateOfSeizure: "2019-01-01",
		dateOfDemolition: "2019-06-01",
		goodsType: "Clothes",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Cumilla",
		seizedBy: "Patrol team S12",
		currentOwner: "Customs",
		monetrayValue: "100000",
		smugglerCaught: false,
	},
	{
		id: 13,
		dateOfSeizure: "2019-01-01",
		goodsType: "Cattle",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Benapole",
		seizedBy: "Patrol team S2",
		currentOwner: "BGB Sector 2",
		smugglerCaught: false,
	},
	{
		id: 14,
		dateOfSeizure: "2019-01-01",
		goodsType: "Weed",
		quantity: "4100",
		unit: "gms",
		seizedAt: "Rajshahi",
		seizedBy: "Patrol team S41",
		currentOwner: "BGB Sector 4",
		smugglerCaught: true,
	},
	{
		id: 15,
		dateOfSeizure: "2019-01-01",
		dateOfDemolition: "2019-06-01",
		goodsType: "Clothes",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Cumilla",
		seizedBy: "Patrol team S12",
		currentOwner: "Customs",
		monetrayValue: "100000",
		smugglerCaught: false,
	},
	{
		id: 16,
		dateOfSeizure: "2019-01-01",
		goodsType: "Cattle",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Benapole",
		seizedBy: "Patrol team S2",
		currentOwner: "BGB Sector 2",
		smugglerCaught: false,
	},
	{
		id: 17,
		dateOfSeizure: "2019-01-01",
		goodsType: "Weed",
		quantity: "4100",
		unit: "gms",
		seizedAt: "Rajshahi",
		seizedBy: "Patrol team S41",
		currentOwner: "BGB Sector 4",
		smugglerCaught: true,
	},
	{
		id: 18,
		dateOfSeizure: "2019-01-01",
		dateOfDemolition: "2019-06-01",
		goodsType: "Clothes",
		quantity: "100",
		unit: "pieces",
		seizedAt: "Cumilla",
		seizedBy: "Patrol team S12",
		currentOwner: "Customs",
		monetrayValue: "100000",
		smugglerCaught: false,
	},
];

export default data;
